name: 'Update Kubernetes Deployment'
description: 'updates the specified deployment file'
inputs:
  release:
    description: 'The release you want to deploy'
    required: true
  container:
    description: 'The name of the container you want to apply the release to.'
    required: true
  deployment:
    description: 'The deployment yaml file'
    required: true
outputs:
  container:
    description: 'The container + release'
runs:
  using: 'node12'
  main: 'src/index.js'