name: 'Update Kubernetes Deployment'
description: 'updates the specified deployment file'
inputs:
  tag:
    description: 'The image release/tag you want to deploy'
    required: true
  name:
    description: 'The name of the container (in the k8s deployment, not the image name) you want to apply the tag to'
    required: true
  deployment:
    description: 'the path to the deployment yaml file'
    required: true
outputs:
  container:
    description: 'The container + tag'
runs:
  using: 'node12'
  main: 'src/index.js'